### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by behelit** [Egorand/android-testing-runtime-permissions#1]
Steps taken:
1. extract zip
2. open project
3. right click ContactSyncTest ->  Run ContactSyncTest

Application starts, permission dialog is shown but all tests fail

What am I doing wrong?
No code changes have been made

`java.lang.AssertionError: View with text <ALLOW> not found!
at me.egorand.contactssync.utils.UiAutomatorUtils.assertViewWithTextIsVisible(UiAutomatorUtils.java:47)
at me.egorand.contactssync.tests.ContactsSyncTest.a_shouldDisplayPermissionRequestDialogAtStartup(ContactsSyncTest.java:68)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)`

**Comment by Egorand** [comment]
Hey,

Thanks for reporting! I tried to run the tests, and indeed they fail. Upon some investigation it turned out that I was trying to match against uppercase names - 'ALLOW', while the uiautomatorviewer showed me that the text in fact is 'Allow'. Oddly enough, when I first wrote those tests it was vice versa - the uiautomatorviewer would show that the text is 'ALLOW'. My guess is that it can be inconsistent between devices, and unfortunately I can't think of a more robust way to fix this, since UiAutomator doesn't support Matchers. It would've been great if there had been a resource string inside the SDK, so that the tests are also safe against different language settings, but I failed to find one. I've pushed the fix, please try it out. Any ideas on a better solution are very welcome. Thanks again!
